#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Armadillo_Animation_Lobby

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "LevelSequence_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Armadillo_Animation_Lobby.Armadillo_Animation_Lobby (Director BP)_C
// 0x0008 (0x0040 - 0x0038)
class UArmadillo_Animation_Lobby__Director_BP__C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0038(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void BP_Armadillo_Iris_Door_01_Event_0(class ABP_Armadillo_IrisDoor_01_C* BP_Armadillo_Iris_Door_01, bool IsClose);
	void BP_Armadillo_Iris_Door_2_Event_0(class ABP_Armadillo_IrisDoor_01_C* BP_Armadillo_Iris_Door_2, bool IsClose);
	void BP_Armadillo_Iris_Door_3_Event_0(class ABP_Armadillo_IrisDoor_01_C* BP_Armadillo_Iris_Door_3, bool IsClose);
	void BP_Armadillo_Iris_Door_4_Event_0(class ABP_Armadillo_IrisDoor_01_C* BP_Armadillo_Iris_Door_4, bool IsClose);
	void ExecuteUbergraph_Armadillo_Animation_Lobby__Director_BP_(int32 EntryPoint);
	void SequenceEvent__ENTRYPOINTArmadillo_Animation_Lobby__Director_BP__0(class ABP_Armadillo_IrisDoor_01_C* BP_Armadillo_Iris_Door_01);
	void SequenceEvent__ENTRYPOINTArmadillo_Animation_Lobby__Director_BP__1(class ABP_Armadillo_IrisDoor_01_C* BP_Armadillo_Iris_Door_01);
	void SequenceEvent__ENTRYPOINTArmadillo_Animation_Lobby__Director_BP__2(class ABP_Armadillo_IrisDoor_01_C* BP_Armadillo_Iris_Door_2);
	void SequenceEvent__ENTRYPOINTArmadillo_Animation_Lobby__Director_BP__3(class ABP_Armadillo_IrisDoor_01_C* BP_Armadillo_Iris_Door_2);
	void SequenceEvent__ENTRYPOINTArmadillo_Animation_Lobby__Director_BP__4(class ABP_Armadillo_IrisDoor_01_C* BP_Armadillo_Iris_Door_3);
	void SequenceEvent__ENTRYPOINTArmadillo_Animation_Lobby__Director_BP__5(class ABP_Armadillo_IrisDoor_01_C* BP_Armadillo_Iris_Door_3);
	void SequenceEvent__ENTRYPOINTArmadillo_Animation_Lobby__Director_BP__6(class ABP_Armadillo_IrisDoor_01_C* BP_Armadillo_Iris_Door_4);
	void SequenceEvent__ENTRYPOINTArmadillo_Animation_Lobby__Director_BP__7(class ABP_Armadillo_IrisDoor_01_C* BP_Armadillo_Iris_Door_4);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Armadillo_Animation_Lobby (Director BP)_C">();
	}
	static class UArmadillo_Animation_Lobby__Director_BP__C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UArmadillo_Animation_Lobby__Director_BP__C>();
	}
};
static_assert(alignof(UArmadillo_Animation_Lobby__Director_BP__C) == 0x000008, "Wrong alignment on UArmadillo_Animation_Lobby__Director_BP__C");
static_assert(sizeof(UArmadillo_Animation_Lobby__Director_BP__C) == 0x000040, "Wrong size on UArmadillo_Animation_Lobby__Director_BP__C");
static_assert(offsetof(UArmadillo_Animation_Lobby__Director_BP__C, UberGraphFrame) == 0x000038, "Member 'UArmadillo_Animation_Lobby__Director_BP__C::UberGraphFrame' has a wrong offset!");

}

