#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ArmadilloRuntime

#include "Basic.hpp"

#include "ArmadilloRuntime_classes.hpp"
#include "ArmadilloRuntime_parameters.hpp"


namespace SDK
{

// Function ArmadilloRuntime.ArmadilloAnimInstance_BGAEnemyGuard.BlueprintUpdateAnim
// (Event, Protected, BlueprintEvent)
// Parameters:
// const float                             DeltaTime                                              (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UArmadilloAnimInstance_BGAEnemyGuard::BlueprintUpdateAnim(const float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArmadilloAnimInstance_BGAEnemyGuard", "BlueprintUpdateAnim");

	Params::ArmadilloAnimInstance_BGAEnemyGuard_BlueprintUpdateAnim Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ArmadilloRuntime.ArmadilloAnimInstance_BGAEnemyGuard.GetCurrentTargetLocation
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bOutValidTarget                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector*                         OutTargetLocation                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UArmadilloAnimInstance_BGAEnemyGuard::GetCurrentTargetLocation(bool* bOutValidTarget, struct FVector* OutTargetLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArmadilloAnimInstance_BGAEnemyGuard", "GetCurrentTargetLocation");

	Params::ArmadilloAnimInstance_BGAEnemyGuard_GetCurrentTargetLocation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bOutValidTarget != nullptr)
		*bOutValidTarget = Parms.bOutValidTarget;

	if (OutTargetLocation != nullptr)
		*OutTargetLocation = std::move(Parms.OutTargetLocation);
}


// Function ArmadilloRuntime.ArmadilloAnimInstance_BGAEnemyGuard.NativeUpdateAim
// (Final, Native, Protected, BlueprintCallable)

void UArmadilloAnimInstance_BGAEnemyGuard::NativeUpdateAim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArmadilloAnimInstance_BGAEnemyGuard", "NativeUpdateAim");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function ArmadilloRuntime.ArmadilloAnimInstance_BGAEnemyGuard.NativeUpdateAttacking
// (Final, Native, Protected, BlueprintCallable)

void UArmadilloAnimInstance_BGAEnemyGuard::NativeUpdateAttacking()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArmadilloAnimInstance_BGAEnemyGuard", "NativeUpdateAttacking");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function ArmadilloRuntime.ArmadilloAnimInstance_BGAEnemyGuard.NativeUpdateCrouch
// (Final, Native, Protected, BlueprintCallable)

void UArmadilloAnimInstance_BGAEnemyGuard::NativeUpdateCrouch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArmadilloAnimInstance_BGAEnemyGuard", "NativeUpdateCrouch");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function ArmadilloRuntime.ArmadilloAnimInstance_BGAEnemyGuard.NativeUpdateMovementDirection
// (Final, Native, Protected, BlueprintCallable)

void UArmadilloAnimInstance_BGAEnemyGuard::NativeUpdateMovementDirection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArmadilloAnimInstance_BGAEnemyGuard", "NativeUpdateMovementDirection");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function ArmadilloRuntime.ArmadilloAnimInstance_BGAEnemyGuard.NativeUpdateSpeedAdjustedPlayRate
// (Final, Native, Protected, BlueprintCallable)

void UArmadilloAnimInstance_BGAEnemyGuard::NativeUpdateSpeedAdjustedPlayRate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArmadilloAnimInstance_BGAEnemyGuard", "NativeUpdateSpeedAdjustedPlayRate");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function ArmadilloRuntime.ArmadilloAnimInstance_BGAEnemyGuard.NativeUpdateTurning
// (Final, Native, Protected, BlueprintCallable)

void UArmadilloAnimInstance_BGAEnemyGuard::NativeUpdateTurning()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArmadilloAnimInstance_BGAEnemyGuard", "NativeUpdateTurning");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function ArmadilloRuntime.ArmadilloAnimInstance_BGAEnemyGuard.NativeUpdateVelocity
// (Final, Native, Protected, BlueprintCallable)

void UArmadilloAnimInstance_BGAEnemyGuard::NativeUpdateVelocity()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArmadilloAnimInstance_BGAEnemyGuard", "NativeUpdateVelocity");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function ArmadilloRuntime.ArmadilloAnimInstance_BGAEnemyGuard.GetRelevantOwningActor
// (Final, Native, Protected, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class AActor*                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class AActor* UArmadilloAnimInstance_BGAEnemyGuard::GetRelevantOwningActor() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArmadilloAnimInstance_BGAEnemyGuard", "GetRelevantOwningActor");

	Params::ArmadilloAnimInstance_BGAEnemyGuard_GetRelevantOwningActor Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ArmadilloRuntime.ArmadilloAnimInstance_BGAEnemyGuard.GetSkeletalMeshComponent
// (Final, Native, Protected, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class USkeletalMeshComponent*           ReturnValue                                            (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class USkeletalMeshComponent* UArmadilloAnimInstance_BGAEnemyGuard::GetSkeletalMeshComponent() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArmadilloAnimInstance_BGAEnemyGuard", "GetSkeletalMeshComponent");

	Params::ArmadilloAnimInstance_BGAEnemyGuard_GetSkeletalMeshComponent Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ArmadilloRuntime.ArmadilloAnimInstance_BGAEnemyGuard.GetSkeletalMeshRootSocketTransform
// (Final, Native, Protected, HasDefaults, BlueprintCallable, Const)
// Parameters:
// struct FTransform                       ReturnValue                                            (Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

struct FTransform UArmadilloAnimInstance_BGAEnemyGuard::GetSkeletalMeshRootSocketTransform() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArmadilloAnimInstance_BGAEnemyGuard", "GetSkeletalMeshRootSocketTransform");

	Params::ArmadilloAnimInstance_BGAEnemyGuard_GetSkeletalMeshRootSocketTransform Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

