#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS20_LandingPage_SmallButton

#include "Basic.hpp"

#include "BPS20_LandingPage_SmallButton_classes.hpp"
#include "BPS20_LandingPage_SmallButton_parameters.hpp"


namespace SDK
{

// Function BPS20_LandingPage_SmallButton.BPS20_LandingPage_SmallButton_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UBPS20_LandingPage_SmallButton_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPage_SmallButton_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPS20_LandingPage_SmallButton.BPS20_LandingPage_SmallButton_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UBPS20_LandingPage_SmallButton_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPage_SmallButton_C", "BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPS20_LandingPage_SmallButton.BPS20_LandingPage_SmallButton_C.ExecuteUbergraph_BPS20_LandingPage_SmallButton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPS20_LandingPage_SmallButton_C::ExecuteUbergraph_BPS20_LandingPage_SmallButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPage_SmallButton_C", "ExecuteUbergraph_BPS20_LandingPage_SmallButton");

	Params::BPS20_LandingPage_SmallButton_C_ExecuteUbergraph_BPS20_LandingPage_SmallButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPS20_LandingPage_SmallButton.BPS20_LandingPage_SmallButton_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBPS20_LandingPage_SmallButton_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPage_SmallButton_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPS20_LandingPage_SmallButton.BPS20_LandingPage_SmallButton_C.Play intro
// (Public, BlueprintCallable, BlueprintEvent)

void UBPS20_LandingPage_SmallButton_C::Play_intro()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPage_SmallButton_C", "Play intro");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPS20_LandingPage_SmallButton.BPS20_LandingPage_SmallButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPS20_LandingPage_SmallButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPage_SmallButton_C", "PreConstruct");

	Params::BPS20_LandingPage_SmallButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

