#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS20_LandingPageButton

#include "Basic.hpp"

#include "BPS20_LandingPageButton_classes.hpp"
#include "BPS20_LandingPageButton_parameters.hpp"


namespace SDK
{

// Function BPS20_LandingPageButton.BPS20_LandingPageButton_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UBPS20_LandingPageButton_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPageButton_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPS20_LandingPageButton.BPS20_LandingPageButton_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UBPS20_LandingPageButton_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPageButton_C", "BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPS20_LandingPageButton.BPS20_LandingPageButton_C.ExecuteUbergraph_BPS20_LandingPageButton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPS20_LandingPageButton_C::ExecuteUbergraph_BPS20_LandingPageButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPageButton_C", "ExecuteUbergraph_BPS20_LandingPageButton");

	Params::BPS20_LandingPageButton_C_ExecuteUbergraph_BPS20_LandingPageButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPS20_LandingPageButton.BPS20_LandingPageButton_C.OnAddedToFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UBPS20_LandingPageButton_C::OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPageButton_C", "OnAddedToFocusPath");

	Params::BPS20_LandingPageButton_C_OnAddedToFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPS20_LandingPageButton.BPS20_LandingPageButton_C.OnDisplayDetailsUpdated
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FBattlePassLandingPageButtonDisplayDetails&NewDisplayDetails                                      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBPS20_LandingPageButton_C::OnDisplayDetailsUpdated(const struct FBattlePassLandingPageButtonDisplayDetails& NewDisplayDetails)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPageButton_C", "OnDisplayDetailsUpdated");

	Params::BPS20_LandingPageButton_C_OnDisplayDetailsUpdated Parms{};

	Parms.NewDisplayDetails = std::move(NewDisplayDetails);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPS20_LandingPageButton.BPS20_LandingPageButton_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBPS20_LandingPageButton_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPageButton_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPS20_LandingPageButton.BPS20_LandingPageButton_C.OnSubscriptionTextureLoaded
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UTexture2D*                       Texture                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPS20_LandingPageButton_C::OnSubscriptionTextureLoaded(class UTexture2D* Texture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPageButton_C", "OnSubscriptionTextureLoaded");

	Params::BPS20_LandingPageButton_C_OnSubscriptionTextureLoaded Parms{};

	Parms.Texture = Texture;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPS20_LandingPageButton.BPS20_LandingPageButton_C.Play intro
// (Public, BlueprintCallable, BlueprintEvent)

void UBPS20_LandingPageButton_C::Play_intro()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPageButton_C", "Play intro");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPS20_LandingPageButton.BPS20_LandingPageButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPS20_LandingPageButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPageButton_C", "PreConstruct");

	Params::BPS20_LandingPageButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPS20_LandingPageButton.BPS20_LandingPageButton_C.SetExtraLock
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ExtraLock                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPS20_LandingPageButton_C::SetExtraLock(bool ExtraLock)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPageButton_C", "SetExtraLock");

	Params::BPS20_LandingPageButton_C_SetExtraLock Parms{};

	Parms.ExtraLock = ExtraLock;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPS20_LandingPageButton.BPS20_LandingPageButton_C.UpdateStatusIcons
// (BlueprintCallable, BlueprintEvent)

void UBPS20_LandingPageButton_C::UpdateStatusIcons()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS20_LandingPageButton_C", "UpdateStatusIcons");

	UObject::ProcessEvent(Func, nullptr);
}

}

