#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DiscoverySubModeLobbyFirstTimeNotification

#include "Basic.hpp"

#include "DiscoverySubModeLobbyFirstTimeNotification_classes.hpp"
#include "DiscoverySubModeLobbyFirstTimeNotification_parameters.hpp"


namespace SDK
{

// Function DiscoverySubModeLobbyFirstTimeNotification.DiscoverySubModeLobbyFirstTimeNotification_C.ExecuteUbergraph_DiscoverySubModeLobbyFirstTimeNotification
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDiscoverySubModeLobbyFirstTimeNotification_C::ExecuteUbergraph_DiscoverySubModeLobbyFirstTimeNotification(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DiscoverySubModeLobbyFirstTimeNotification_C", "ExecuteUbergraph_DiscoverySubModeLobbyFirstTimeNotification");

	Params::DiscoverySubModeLobbyFirstTimeNotification_C_ExecuteUbergraph_DiscoverySubModeLobbyFirstTimeNotification Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DiscoverySubModeLobbyFirstTimeNotification.DiscoverySubModeLobbyFirstTimeNotification_C.HideNotification
// (BlueprintCallable, BlueprintEvent)

void UDiscoverySubModeLobbyFirstTimeNotification_C::HideNotification()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DiscoverySubModeLobbyFirstTimeNotification_C", "HideNotification");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DiscoverySubModeLobbyFirstTimeNotification.DiscoverySubModeLobbyFirstTimeNotification_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UDiscoverySubModeLobbyFirstTimeNotification_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DiscoverySubModeLobbyFirstTimeNotification_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DiscoverySubModeLobbyFirstTimeNotification.DiscoverySubModeLobbyFirstTimeNotification_C.ShowNotification
// (BlueprintCallable, BlueprintEvent)

void UDiscoverySubModeLobbyFirstTimeNotification_C::ShowNotification()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DiscoverySubModeLobbyFirstTimeNotification_C", "ShowNotification");

	UObject::ProcessEvent(Func, nullptr);
}

}

