#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Fortnite_M_Avg_Player_Sprint_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// ScriptStruct Fortnite_M_Avg_Player_Sprint_AnimBP.Fortnite_M_Avg_Player_Sprint_AnimBP_C.AnimBlueprintGeneratedConstantData
// 0x01B7 (0x01B8 - 0x0001)
struct Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData final : public FAnimBlueprintConstantData
{
public:
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_374;                                // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_375;                                // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBlendListTransitionType                      __EnumProperty_376;                                // 0x000C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_377;                               // 0x0010(0x0010)(BlueprintVisible, EditFixedSize)
	class FName                                   __NameProperty_378;                                // 0x0020(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimSequenceBase*                      __AnimSequenceBase_379;                            // 0x0028(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class FName                                   __NameProperty_380;                                // 0x0030(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimSequenceBase*                      __AnimSequenceBase_381;                            // 0x0038(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UAnimSequenceBase*                      __AnimSequenceBase_382;                            // 0x0040(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class FName                                   __NameProperty_383;                                // 0x0048(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimSequenceBase*                      __AnimSequenceBase_384;                            // 0x0050(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UAnimSequenceBase*                      __AnimSequenceBase_385;                            // 0x0058(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class FName                                   __NameProperty_386;                                // 0x0060(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_387;                               // 0x0068(0x0010)(BlueprintVisible, EditFixedSize)
	class UBlendSpace*                            __BlendSpace_388;                                  // 0x0078(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	struct FInputScaleBiasClampConstants          __StructProperty_389;                              // 0x0080(0x002C)(BlueprintVisible, NoDestructor)
	float                                         __FloatProperty_390;                               // 0x00AC(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimSyncMethod                               __EnumProperty_391;                                // 0x00B0(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimGroupRole                                __ByteProperty_392;                                // 0x00B1(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B2[0x6];                                       // 0x00B2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UBlendSpace*                            __BlendSpace_393;                                  // 0x00B8(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UBlendSpace*                            __BlendSpace_394;                                  // 0x00C0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          __BoolProperty_395;                                // 0x00C8(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C9[0x3];                                       // 0x00C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_396;                               // 0x00CC(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimSyncMethod                               __EnumProperty_397;                                // 0x00D0(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimGroupRole                                __ByteProperty_398;                                // 0x00D1(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D2[0x2];                                       // 0x00D2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_399;                                // 0x00D4(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBlendProfile*                          __BlendProfile_400;                                // 0x00D8(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UCurveFloat*                            __CurveFloat_401;                                  // 0x00E0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          __BoolProperty_402;                                // 0x00E8(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAlphaBlendOption                             __EnumProperty_403;                                // 0x00E9(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBlendListTransitionType                      __EnumProperty_404;                                // 0x00EA(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EB[0x5];                                       // 0x00EB(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_405;                               // 0x00F0(0x0010)(BlueprintVisible, EditFixedSize)
	class FName                                   __NameProperty_406;                                // 0x0100(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_407;                                // 0x0104(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnimNodeFunctionRef                   __StructProperty_408;                              // 0x0108(0x0018)(BlueprintVisible, NoDestructor)
	struct FAnimSubsystem_PropertyAccess          AnimBlueprintExtension_PropertyAccess;             // 0x0120(0x0080)()
	struct FAnimSubsystem_Base                    AnimBlueprintExtension_Base;                       // 0x01A0(0x0018)()
};
static_assert(alignof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData) == 0x0001B8, "Wrong size on Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_374) == 0x000004, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_374' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_375) == 0x000008, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_375' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __EnumProperty_376) == 0x00000C, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__EnumProperty_376' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __ArrayProperty_377) == 0x000010, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__ArrayProperty_377' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_378) == 0x000020, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_378' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __AnimSequenceBase_379) == 0x000028, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__AnimSequenceBase_379' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_380) == 0x000030, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_380' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __AnimSequenceBase_381) == 0x000038, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__AnimSequenceBase_381' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __AnimSequenceBase_382) == 0x000040, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__AnimSequenceBase_382' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_383) == 0x000048, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_383' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __AnimSequenceBase_384) == 0x000050, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__AnimSequenceBase_384' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __AnimSequenceBase_385) == 0x000058, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__AnimSequenceBase_385' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_386) == 0x000060, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_386' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __ArrayProperty_387) == 0x000068, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__ArrayProperty_387' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __BlendSpace_388) == 0x000078, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__BlendSpace_388' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __StructProperty_389) == 0x000080, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__StructProperty_389' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __FloatProperty_390) == 0x0000AC, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__FloatProperty_390' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __EnumProperty_391) == 0x0000B0, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__EnumProperty_391' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __ByteProperty_392) == 0x0000B1, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__ByteProperty_392' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __BlendSpace_393) == 0x0000B8, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__BlendSpace_393' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __BlendSpace_394) == 0x0000C0, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__BlendSpace_394' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __BoolProperty_395) == 0x0000C8, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__BoolProperty_395' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __FloatProperty_396) == 0x0000CC, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__FloatProperty_396' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __EnumProperty_397) == 0x0000D0, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__EnumProperty_397' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __ByteProperty_398) == 0x0000D1, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__ByteProperty_398' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_399) == 0x0000D4, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_399' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __BlendProfile_400) == 0x0000D8, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__BlendProfile_400' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __CurveFloat_401) == 0x0000E0, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__CurveFloat_401' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __BoolProperty_402) == 0x0000E8, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__BoolProperty_402' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __EnumProperty_403) == 0x0000E9, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__EnumProperty_403' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __EnumProperty_404) == 0x0000EA, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__EnumProperty_404' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __ArrayProperty_405) == 0x0000F0, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__ArrayProperty_405' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_406) == 0x000100, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_406' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_407) == 0x000104, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_407' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, __StructProperty_408) == 0x000108, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::__StructProperty_408' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_PropertyAccess) == 0x000120, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_Base) == 0x0001A0, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_Base' has a wrong offset!");

// ScriptStruct Fortnite_M_Avg_Player_Sprint_AnimBP.Fortnite_M_Avg_Player_Sprint_AnimBP_C.AnimBlueprintGeneratedMutableData
// 0x008F (0x0090 - 0x0001)
struct Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData final : public FAnimBlueprintMutableData
{
public:
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty;                                   // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimSequenceBase*                      __AnimSequenceBase_0;                              // 0x0008(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	float                                         __FloatProperty_1;                                 // 0x0010(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimSequenceBase*                      __AnimSequenceBase_2;                              // 0x0018(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          __BoolProperty_3;                                  // 0x0020(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimSequenceBase*                      __AnimSequenceBase_4;                              // 0x0028(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UAnimSequenceBase*                      __AnimSequenceBase_5;                              // 0x0030(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          __BoolProperty_6;                                  // 0x0038(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_7;                                  // 0x0039(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_8;                                  // 0x003A(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_9;                                  // 0x003B(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_10;                                // 0x003C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimSequenceBase*                      __AnimSequenceBase_11;                             // 0x0040(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          __BoolProperty_12;                                 // 0x0048(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimSequenceBase*                      __AnimSequenceBase_13;                             // 0x0050(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UAnimSequenceBase*                      __AnimSequenceBase_14;                             // 0x0058(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UAnimSequenceBase*                      __AnimSequenceBase_15;                             // 0x0060(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          __BoolProperty_16;                                 // 0x0068(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimSequenceBase*                      __AnimSequenceBase_17;                             // 0x0070(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	float                                         __FloatProperty_18;                                // 0x0078(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_19;                                // 0x007C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_20;                                // 0x0080(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_21;                                // 0x0084(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_22;                                 // 0x0088(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData) == 0x000008, "Wrong alignment on Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData");
static_assert(sizeof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData) == 0x000090, "Wrong size on Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __FloatProperty) == 0x000004, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__FloatProperty' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __AnimSequenceBase_0) == 0x000008, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__AnimSequenceBase_0' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __FloatProperty_1) == 0x000010, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__FloatProperty_1' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __AnimSequenceBase_2) == 0x000018, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__AnimSequenceBase_2' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __BoolProperty_3) == 0x000020, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__BoolProperty_3' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __AnimSequenceBase_4) == 0x000028, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__AnimSequenceBase_4' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __AnimSequenceBase_5) == 0x000030, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__AnimSequenceBase_5' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __BoolProperty_6) == 0x000038, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__BoolProperty_6' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __BoolProperty_7) == 0x000039, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__BoolProperty_7' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __BoolProperty_8) == 0x00003A, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__BoolProperty_8' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __BoolProperty_9) == 0x00003B, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__BoolProperty_9' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __FloatProperty_10) == 0x00003C, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__FloatProperty_10' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __AnimSequenceBase_11) == 0x000040, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__AnimSequenceBase_11' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __BoolProperty_12) == 0x000048, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__BoolProperty_12' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __AnimSequenceBase_13) == 0x000050, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__AnimSequenceBase_13' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __AnimSequenceBase_14) == 0x000058, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__AnimSequenceBase_14' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __AnimSequenceBase_15) == 0x000060, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__AnimSequenceBase_15' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __BoolProperty_16) == 0x000068, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__BoolProperty_16' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __AnimSequenceBase_17) == 0x000070, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__AnimSequenceBase_17' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __FloatProperty_18) == 0x000078, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__FloatProperty_18' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __FloatProperty_19) == 0x00007C, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__FloatProperty_19' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __FloatProperty_20) == 0x000080, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__FloatProperty_20' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __FloatProperty_21) == 0x000084, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__FloatProperty_21' has a wrong offset!");
static_assert(offsetof(Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData, __BoolProperty_22) == 0x000088, "Member 'Fortnite_M_Avg_Player_Sprint_AnimBP::FAnimBlueprintGeneratedMutableData::__BoolProperty_22' has a wrong offset!");

}

