#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HoagieUI

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// Class HoagieUI.FortHoagieVehicleReticle
// 0x0008 (0x0378 - 0x0370)
class UFortHoagieVehicleReticle final : public UFortAthenaVehicleDashboardWidget
{
public:
	class AFortHoagieVehicle*                     OwningHoagieVehicle;                               // 0x0370(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void OnSetupComplete(bool bVehicleUsesFuelSystem);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortHoagieVehicleReticle">();
	}
	static class UFortHoagieVehicleReticle* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortHoagieVehicleReticle>();
	}
};
static_assert(alignof(UFortHoagieVehicleReticle) == 0x000008, "Wrong alignment on UFortHoagieVehicleReticle");
static_assert(sizeof(UFortHoagieVehicleReticle) == 0x000378, "Wrong size on UFortHoagieVehicleReticle");
static_assert(offsetof(UFortHoagieVehicleReticle, OwningHoagieVehicle) == 0x000370, "Member 'UFortHoagieVehicleReticle::OwningHoagieVehicle' has a wrong offset!");

}

