#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerSurveyRatingChoice

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PlayerSurveyRatingChoice.PlayerSurveyRatingChoice_C
// 0x0010 (0x0FC0 - 0x0FB0)
class UPlayerSurveyRatingChoice_C final : public UFortPlayerSurveyRatingChoiceBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0FB0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonActionWidget*                    InputActionWidget_Select;                          // 0x0FB8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BP_OnDeselected();
	void BP_OnHovered();
	void BP_OnSelected();
	void BP_OnUnhovered();
	void ExecuteUbergraph_PlayerSurveyRatingChoice(int32 EntryPoint);
	void GetCurrentButtonBrush(struct FSlateBrush* CurrentBrush);
	void OnInitialized();
	void OnSurveyResetChoice();
	void UpdateInputActionRenderOpacity();
	void UpdateTextStyle();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PlayerSurveyRatingChoice_C">();
	}
	static class UPlayerSurveyRatingChoice_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerSurveyRatingChoice_C>();
	}
};
static_assert(alignof(UPlayerSurveyRatingChoice_C) == 0x000010, "Wrong alignment on UPlayerSurveyRatingChoice_C");
static_assert(sizeof(UPlayerSurveyRatingChoice_C) == 0x000FC0, "Wrong size on UPlayerSurveyRatingChoice_C");
static_assert(offsetof(UPlayerSurveyRatingChoice_C, UberGraphFrame) == 0x000FB0, "Member 'UPlayerSurveyRatingChoice_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UPlayerSurveyRatingChoice_C, InputActionWidget_Select) == 0x000FB8, "Member 'UPlayerSurveyRatingChoice_C::InputActionWidget_Select' has a wrong offset!");

}

