#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Seven_VS_IO_UI

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// Class Seven_VS_IO_UI.Seven_VS_IO_StatusWidget
// 0x0048 (0x0328 - 0x02E0)
class USeven_VS_IO_StatusWidget final : public UFortHUDElementWidget
{
public:
	uint8                                         Pad_2E0[0x40];                                     // 0x02E0(0x0040)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFortPrioritizedWidgetData             PrioritizationData;                                // 0x0320(0x0002)(Edit, NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_322[0x6];                                      // 0x0322(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	const class FText GetPOINameFromTag(const struct FGameplayTag& POITag) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Seven_VS_IO_StatusWidget">();
	}
	static class USeven_VS_IO_StatusWidget* GetDefaultObj()
	{
		return GetDefaultObjImpl<USeven_VS_IO_StatusWidget>();
	}
};
static_assert(alignof(USeven_VS_IO_StatusWidget) == 0x000008, "Wrong alignment on USeven_VS_IO_StatusWidget");
static_assert(sizeof(USeven_VS_IO_StatusWidget) == 0x000328, "Wrong size on USeven_VS_IO_StatusWidget");
static_assert(offsetof(USeven_VS_IO_StatusWidget, PrioritizationData) == 0x000320, "Member 'USeven_VS_IO_StatusWidget::PrioritizationData' has a wrong offset!");

}

